Repository datt16/PC-Phone_Site, pull requests merged in 2021-01, with the labels that each got.

#34 細かい部分の変更1
  src/pages/index.jsx
  src/styles/Header.module.css
  src/styles/Home.module.css
Labels: design

#38 記事のフォーマット、lint修正、ページ生成
  .markdownlint.json
  articles/AQUOS-sense4.md
  articles/AQUOS-zero5G-basic.md
  articles/Galaxy_s20.md
  articles/Google-Pixel.md
  articles/HUAWEI-P30-lite.md
  articles/ROG-Phone-3.md
  articles/XPS-13.md
  articles/Xperia-10-2.md
  articles/Xperia5-2.md
  articles/iPad-Pro.md
  articles/iPhone-SE.md
  articles/iPhone-X.md
  articles/iPhone12.md
  articles/iphone11.md
  package-lock.json
  package.json
  src/lib/articles.js
Labels: help wanted

#40 端末の寸法を表示するようにした
  src/components/devicePreview.jsx
  src/pages/device/[id].jsx
  src/pages/index.jsx
  src/styles/Device.module.css
  src/styles/DevicePreview.module.css
Labels: design, enhancement

#41 細かい修正
  src/components/footer.jsx
Labels: bug, design, enhancement

#44 DevicePreview表示時のエラー直した
  package-lock.json
  src/components/devicePreview.jsx
  src/styles/DevicePreview.module.css
Labels: bug

#49 小さい修正
  .editorconfig
  src/components/deviceSpecCard.jsx
  src/pages/device/[id].jsx
  src/styles/Device.module.css
  src/styles/DevicePreview.module.css
  src/styles/DeviceSpec.module.scss
  src/styles/Footer.module.css
  src/styles/Header.module.css
  src/styles/Home.module.css
  src/styles/ItemCard.module.css
  src/styles/Modal.module.css
  src/styles/SearchBox.module.css
Labels: design

#50 プレビューの大きさ直した
  src/components/devicePreview.jsx
  src/pages/device/[id].jsx
  src/styles/Device.module.css
  src/styles/DevicePreview.module.css
  src/styles/Home.module.css
  src/styles/ItemCard.module.css
Labels: bug, design

#52 Markdown部分のデザイン
  src/pages/device/[id].jsx
  src/styles/Device.module.css
Labels: design

#56 細かいところの修正
  src/components/devicePreview.jsx
  src/styles/Device.module.css
  src/styles/DevicePreview.module.css
  src/styles/Footer.module.css
  src/styles/Header.module.css
Labels: design

#58 記事追加 & PC対応
  articles/A5-Pro-CC.md
  articles/AQUOS-sense4.md
  articles/AQUOS-zero5G-basic.md
  articles/Galaxy-S20.md
  articles/Google-Pixel-5.md
  articles/HUAWEI-P30-lite.md
  articles/ROG-Phone-3.md
  articles/XPS-13.md
  articles/Xperia-10-2.md
  articles/Xperia-5-2.md
  articles/iPhone-11.md
  articles/iPhone-12.md
  articles/iPhone-SE.md
  cli/gen-articles.js
  src/components/deviceSpec.jsx
  src/components/deviceSpecCard.jsx
  src/lib/articles.js
  src/pages/device/[id].jsx
Labels: enhancement, logic

#59 DevicePreview PC対応
  src/components/devicePreview.jsx
  src/pages/device/[id].jsx
  src/styles/DevicePreview.module.css
Labels: design

#62 MacBook Pro の記事
  articles/MacBook-Pro.md
  src/lib/articles.js
  src/styles/Device.module.css
  src/styles/DevicePreview.module.css
  src/styles/DeviceSpec.module.scss
Labels: design, enhancement

#65 ホバーした時にはみ出さないように
  src/styles/DevicePreview.module.css
  src/styles/ItemCard.module.css
Labels: bug, design

#70 Aboutページ追加
  articles/AQUOS-sense4.md
  public/AQUOS-sense4.jpg
  public/no-image.svg
  src/components/footer.jsx
  src/components/header.jsx
  src/components/itemCard.jsx
  src/lib/articles.js
  src/pages/about.jsx
  src/pages/device/[id].jsx
  src/styles/About.module.css
  src/styles/Device.module.css
  src/styles/Footer.module.css
Labels: design, enhancement
